### ISSUE TITLE
Installation error - Windows 10

### ISSUE THREAD

**Issue by Tiberriver256** [azu/inkdrop-excalidraw#3]
Hello,

I'm unable to install the extension. I get the following error message:

![image](https://user-images.githubusercontent.com/6989492/117478051-b0872200-af2c-11eb-9366-8349d9ee8f3d.png)

**Comment by Tiberriver256** [comment]
Might suggest using `shx`?

https://stackoverflow.com/questions/59822554/recursively-copy-files-cross-platform-via-npm-script

**Comment by azu** [comment]
Thanks for the report!
Ah, I do not expect to run `postinstall` during `ipm install`.

**Comment by azu** [comment]
I've released [v1.0.2](https://github.com/azu/inkdrop-excalidraw/releases/tag/v1.0.2).
Please try again.

**Comment by Tiberriver256** [comment]
![image](https://user-images.githubusercontent.com/6989492/117481420-f940da00-af30-11eb-81ae-b0794a046c8c.png)

🎊🎊🎊

Thank you!
