### ISSUE TITLE
'No settings for this plugin'

### ISSUE THREAD

**Issue by Tiberriver256** [azu/inkdrop-excalidraw#4]
![image](https://user-images.githubusercontent.com/6989492/117492025-08c71f80-af3f-11eb-84f2-f9e8b776b104.png)

I'm wanting to set the saveDir setting and for some reason it doesn't want to let me edit the setting from the preferences window. Any recommendations?

**Comment by azu** [comment]
It is strange. The reason for the error is that published files do not include `lib/` directory.
I've committed lib/ and republished it. 
https://github.com/azu/inkdrop-excalidraw/commit/4eba372061057811cec8167ca0a86e9da28970d0
📝 apm/ipm does not support `files` or `.npmignore`… https://github.com/atom/apm/issues/498


Please try again.

**Comment by Tiberriver256** [comment]
Haha nice! Nailed it. Thanks again!

![image](https://user-images.githubusercontent.com/6989492/117519626-514c0080-af72-11eb-9edf-c21f41fe9c11.png)
