### ISSUE TITLE
Doesn't like Windows file paths

### ISSUE THREAD

**Issue by Tiberriver256** [azu/inkdrop-excalidraw#5]
I can write my paths with forward slashes and it works but I thought you might want to know. 

![image](https://user-images.githubusercontent.com/6989492/117520474-58750d80-af76-11eb-95f2-5aebd329d560.png)

It seems to come in with the backslashes converted to %5C which makes it fail the path test.

![image](https://user-images.githubusercontent.com/6989492/117520502-7cd0ea00-af76-11eb-9a9d-c3163969bf3c.png)

My settings:

![image](https://user-images.githubusercontent.com/6989492/117520530-9f630300-af76-11eb-9a98-83ef351e39e6.png)

**Comment by azu** [comment]
<https://github.com/azu/inkdrop-excalidraw/blob/1e96cbe12720be653f38831b1029eb7720e62474/src/remark-anchor.js#L16>
Fmm, it seems that remark-react escape backslash as `%5C` automatically.

![image](https://user-images.githubusercontent.com/19714/117520784-f99aad00-afe4-11eb-84d2-38091a4ee219.png)

**Comment by azu** [comment]
Probably, we need to use `file:///path/to/file` intead of absolute path.

My concern is that I do not know that following markdown work on Windows.
```markdown
![](file:///path/to/img.png)
```

**Comment by azu** [comment]
Probably, I've fixed it by using the `file:///`  protocol.
https://github.com/azu/inkdrop-excalidraw/releases/tag/v2.0.0
📝 The old file paths should be rewritten manually. 

The new version's "Create Excalidraw" will generate `[!Excalidraw](file://path/to/file.excalidraw)`.
Can you try it?

**Comment by Tiberriver256** [comment]
Nice! Worked like a charm. Thanks again!

![image](https://user-images.githubusercontent.com/6989492/117551128-21ecd080-b012-11eb-8282-01537207717d.png)
